name: "Demo service Infrastructure Change Management Pipeline with GitHub Actions"

on:
  push:
    branches:
      - main
      - dev
      - local-dev
    paths:
      - practice/api_gateway_to_lambda_docker_to_dynamodb/**
  pull_request:
    branches:
      - main
      - dev
      - local-dev
    paths:
      - practice/api_gateway_to_lambda_docker_to_dynamodb/**

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Set environment variables
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "TF_DIR=./practice/api_gateway_to_lambda_docker_to_dynamodb" >> $GITHUB_ENV
            echo "TF_VARS_FILE=prod.tfvars" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "TF_DIR=./practice/api_gateway_to_lambda_docker_to_dynamodb" >> $GITHUB_ENV
            echo "TF_VARS_FILE=dev.tfvars" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/local-dev" ]]; then
            echo "ENVIRONMENT=local-dev" >> $GITHUB_ENV
            echo "TF_DIR=./practice/api_gateway_to_lambda_docker_to_dynamodb" >> $GITHUB_ENV
            echo "TF_VARS_FILE=local-dev.tfvars" >> $GITHUB_ENV
          else
            echo "Unsupported branch: ${{ github.ref }}"
            exit 1
          fi

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "TF_DIR: ${{ env.TF_DIR }}"
          echo "TF_VARS_FILE: ${{ env.TF_VARS_FILE }}"
          ls -la ${{ env.TF_DIR }}

      - name: Terraform init
        id: init
        run: terraform init -backend-config="${{ env.ENVIRONMENT }}.tfbackend" -reconfigure
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          if [ -z "${{ env.TF_VARS_FILE }}" ]; then
            echo "Error: TF_VARS_FILE is not set"
            exit 1
          fi
          if [ ! -f "${{ env.TF_VARS_FILE }}" ]; then
            echo "Error: ${{ env.TF_VARS_FILE }} does not exist"
            exit 1
          fi
          terraform plan -no-color -input=false -var-file="${{ env.TF_VARS_FILE }}"
        working-directory: ${{ env.TF_DIR }}
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.event.created == false
        run: |
          if [ -z "${{ env.TF_VARS_FILE }}" ]; then
            echo "Error: TF_VARS_FILE is not set"
            exit 1
          fi
          if [ ! -f "${{ env.TF_VARS_FILE }}" ]; then
            echo "Error: ${{ env.TF_VARS_FILE }} does not exist"
            exit 1
          fi
          terraform apply -auto-approve -input=false -var-file="${{ env.TF_VARS_FILE }}"
        working-directory: ${{ env.TF_DIR }}
